### ISSUE TITLE
Safe Locks leaderbaord not sorting correctly.

### ISSUE THREAD

**Issue by ThePhilderbeast** [Lockpickers-United/lpu-belt-explorer#124]
Due to missing data for some rows, the table for the safe locks leader board does not sort as expected when changing between owned, cracked and wish listed.

Additionally it appears to be defaulting to owned rather then cracked as I expect the default sort should be.

**Comment by mgsecure** [comment]
Data fixed, thanks for pointing it out. Sort matches the locks one...
