### ISSUE TITLE
Old information.html page?

### ISSUE THREAD

**Issue by tswfi** [Lockpickers-United/lpu-belt-explorer#77]
Not sure where / how you want these to be communicated but lets try here :)

I was looking at adding a bit more to brown belt "create specialized tool" bit (now it says what does not suffice like bobby pins etc, but there is no "this will be ok" example).

While doing a git grep to find the correct place I noticed that there are two "information" pages.

from: src/resources/information.html
rendered in: https://lpubelts.com/locks/information.html

from: src/resources/info.md
rendered in: https://lpubelts.com/#/info

It looks like the `information.html` is old and should probably be removed completely?

**Comment by NiXXeD** [comment]
The static html is used for search engines, since the site isn't SSR. This is intentional.
