### ISSUE TITLE
Clarification for brown belt "specialized tool"

### ISSUE THREAD

**Issue by tswfi** [Lockpickers-United/lpu-belt-explorer#78]
As a new picker and new to the whole scene this site offers quite a bit of valuable information.

I was left wondering what the "specialized tool" requirement for brown belt means. It does say a bent bobby pin would not suffice but does not clarify what would.

Does Abloy classic pick made from injector pin fill the requirement?
What about some 3d printed follower sets?

Giving some kind of example would make this quite a bit clearer for newcomers.

I'm happy to make a pull request after getting some clarification on what to add to the text to make it clearer on what is required :)

**Comment by NiXXeD** [comment]
All of the content in the site is managed by LPU admins. The best place to submit suggestions to wording changes and additions is on the discord in #belt-explorer or #mod-requests.
